import { generatePalette } from '@/lib/utils/colour';
import { Transaction } from '../Transactions/schema';

// export const weekColors = ['#f97316', '#22c55e', '#3b82f6', '#8b5cf6'];
export const dayKeys = ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'];
export type DayKey = (typeof dayKeys)[number];
export const weekColors = ['#dab2ff', '#ad46ff', '#8200db', '#59168b', '#59168b', '#3c0366'];
export const generatedPalette: string[] = Object.values(generatePalette('MY SEED TEST NEW SPd@.'))
    .map((colour) => colour)
    .reverse();
export const dayLabels: Record<DayKey, string> = {
    Su: 'S',
    Mo: 'M',
    Tu: 'T',
    We: 'W',
    Th: 'T',
    Fr: 'F',
    Sa: 'S',
};
export const spendOverviewPalette = [
    '#9810fa',
    '#c800de',
    '#e60076',
    '#e17100',
    '#009689',
    '#e17100',
];

export const mockTransactions: Partial<Transaction>[] = [
    {
        id: '1',
        type: 'debit',
        amount: 1200,
        currency: 'USD',
        category: '🍔 Food',
        created_at: new Date().toISOString(),
    },
    {
        id: '2',
        type: 'debit',
        amount: 350,
        currency: 'USD',
        category: '🚌 Transport',
        created_at: new Date().toISOString(),
    },
    {
        id: '3',
        type: 'debit',
        amount: 75,
        currency: 'USD',
        category: '☕ Coffee',
        created_at: new Date().toISOString(),
    },
    {
        id: '4',
        type: 'debit',
        amount: 500,
        currency: 'USD',
        category: '🎬 Entertainment',
        created_at: new Date().toISOString(),
    },
    {
        id: '5',
        type: 'debit',
        amount: 210,
        currency: 'USD',
        category: '📱 Subscriptions',
        created_at: new Date().toISOString(),
    },
    {
        id: '6',
        type: 'debit',
        amount: 90,
        currency: 'USD',
        category: '🍦 Snacks',
        created_at: new Date().toISOString(),
    },
    {
        id: '7',
        type: 'debit',
        amount: 450,
        currency: 'USD',
        category: '🛒 Groceries',
        created_at: new Date().toISOString(),
    },
    {
        id: '8',
        type: 'debit',
        amount: 650,
        currency: 'USD',
        category: '🚖 Taxi',
        created_at: new Date().toISOString(),
    },
    {
        id: '9',
        type: 'debit',
        amount: 300,
        currency: 'USD',
        category: '🏋️‍♂️ Fitness',
        created_at: new Date().toISOString(),
    },
    {
        id: '10',
        type: 'debit',
        amount: 180,
        currency: 'USD',
        category: '📚 Books',
        created_at: new Date().toISOString(),
    },
    {
        id: '11',
        type: 'debit',
        amount: 95,
        currency: 'USD',
        category: '🍕 Fast Food',
        created_at: new Date().toISOString(),
    },
    {
        id: '12',
        type: 'debit',
        amount: 220,
        currency: 'USD',
        category: '🎮 Gaming',
        created_at: new Date().toISOString(),
    },
    {
        id: '13',
        type: 'debit',
        amount: 140,
        currency: 'USD',
        category: '💇 Grooming',
        created_at: new Date().toISOString(),
    },
    {
        id: '14',
        type: 'debit',
        amount: 400,
        currency: 'USD',
        category: '👕 Clothing',
        created_at: new Date().toISOString(),
    },
    {
        id: '15',
        type: 'debit',
        amount: 330,
        currency: 'USD',
        category: '🛍️ Shopping',
        created_at: new Date().toISOString(),
    },
    {
        id: '16',
        type: 'debit',
        amount: 50,
        currency: 'USD',
        category: '🥤 Drinks',
        created_at: new Date().toISOString(),
    },
    {
        id: '17',
        type: 'debit',
        amount: 275,
        currency: 'USD',
        category: '🖥️ Software',
        created_at: new Date().toISOString(),
    },
    {
        id: '18',
        type: 'debit',
        amount: 60,
        currency: 'USD',
        category: '🍩 Dessert',
        created_at: new Date().toISOString(),
    },
    {
        id: '19',
        type: 'debit',
        amount: 490,
        currency: 'USD',
        category: '💡 Utilities',
        created_at: new Date().toISOString(),
    },
    {
        id: '20',
        type: 'debit',
        amount: 200,
        currency: 'USD',
        category: '📺 Streaming',
        created_at: new Date().toISOString(),
    },
    {
        id: '21',
        type: 'debit',
        amount: 370,
        currency: 'USD',
        category: '🐶 Pets',
        created_at: new Date().toISOString(),
    },
    {
        id: '22',
        type: 'debit',
        amount: 85,
        currency: 'USD',
        category: '🌮 Dining Out',
        created_at: new Date().toISOString(),
    },
    {
        id: '23',
        type: 'debit',
        amount: 260,
        currency: 'USD',
        category: '🚲 Transport',
        created_at: new Date().toISOString(),
    },
    {
        id: '24',
        type: 'debit',
        amount: 115,
        currency: 'USD',
        category: '🍿 Cinema',
        created_at: new Date().toISOString(),
    },
    {
        id: '25',
        type: 'debit',
        amount: 45,
        currency: 'USD',
        category: '🍫 Candy',
        created_at: new Date().toISOString(),
    },
    {
        id: '26',
        type: 'debit',
        amount: 160,
        currency: 'USD',
        category: '🖼️ Art',
        created_at: new Date().toISOString(),
    },
    {
        id: '27',
        type: 'debit',
        amount: 700,
        currency: 'USD',
        category: '🏠 Rent',
        created_at: new Date().toISOString(),
    },
    {
        id: '28',
        type: 'debit',
        amount: 430,
        currency: 'USD',
        category: '🚿 Hygiene',
        created_at: new Date().toISOString(),
    },
    {
        id: '29',
        type: 'debit',
        amount: 310,
        currency: 'USD',
        category: '🩺 Health',
        created_at: new Date().toISOString(),
    },
    {
        id: '30',
        type: 'debit',
        amount: 500,
        currency: 'USD',
        category: '✈️ Travel',
        created_at: new Date().toISOString(),
    },

    // Credits
    {
        id: '31',
        type: 'credit',
        amount: 2200,
        currency: 'USD',
        category: '💼 Salary',
        created_at: new Date().toISOString(),
    },
    {
        id: '32',
        type: 'credit',
        amount: 150,
        currency: 'USD',
        category: '🎁 Gift',
        created_at: new Date().toISOString(),
    },
    {
        id: '33',
        type: 'credit',
        amount: 800,
        currency: 'USD',
        category: '📈 Investments',
        created_at: new Date().toISOString(),
    },
    {
        id: '34',
        type: 'credit',
        amount: 120,
        currency: 'USD',
        category: '💸 Cashback',
        created_at: new Date().toISOString(),
    },
    {
        id: '35',
        type: 'credit',
        amount: 600,
        currency: 'USD',
        category: '🏦 Bank Transfer',
        created_at: new Date().toISOString(),
    },
    {
        id: '36',
        type: 'credit',
        amount: 450,
        currency: 'USD',
        category: '👨‍👩‍👧 Family Support',
        created_at: new Date().toISOString(),
    },
    {
        id: '37',
        type: 'credit',
        amount: 1000,
        currency: 'USD',
        category: '📊 Stocks',
        created_at: new Date().toISOString(),
    },
    {
        id: '38',
        type: 'credit',
        amount: 200,
        currency: 'USD',
        category: '🪙 Crypto',
        created_at: new Date().toISOString(),
    },
    {
        id: '39',
        type: 'credit',
        amount: 750,
        currency: 'USD',
        category: '🛍️ Refund',
        created_at: new Date().toISOString(),
    },
    {
        id: '40',
        type: 'credit',
        amount: 320,
        currency: 'USD',
        category: '🎉 Bonus',
        created_at: new Date().toISOString(),
    },
    {
        id: '41',
        type: 'credit',
        amount: 900,
        currency: 'USD',
        category: '🧾 Reimbursement',
        created_at: new Date().toISOString(),
    },
    {
        id: '42',
        type: 'credit',
        amount: 250,
        currency: 'USD',
        category: '🎂 Gift',
        created_at: new Date().toISOString(),
    },
    {
        id: '43',
        type: 'credit',
        amount: 500,
        currency: 'USD',
        category: '🏆 Prize',
        created_at: new Date().toISOString(),
    },
    {
        id: '44',
        type: 'credit',
        amount: 1400,
        currency: 'USD',
        category: '💼 Salary',
        created_at: new Date().toISOString(),
    },
    {
        id: '45',
        type: 'credit',
        amount: 380,
        currency: 'USD',
        category: '📦 Side Hustle',
        created_at: new Date().toISOString(),
    },
    {
        id: '46',
        type: 'credit',
        amount: 270,
        currency: 'USD',
        category: '💵 Allowance',
        created_at: new Date().toISOString(),
    },
    {
        id: '47',
        type: 'credit',
        amount: 1100,
        currency: 'USD',
        category: '🏦 Interest',
        created_at: new Date().toISOString(),
    },
    {
        id: '48',
        type: 'credit',
        amount: 330,
        currency: 'USD',
        category: '📲 Mobile Money',
        created_at: new Date().toISOString(),
    },
    {
        id: '49',
        type: 'credit',
        amount: 720,
        currency: 'USD',
        category: '🏅 Award',
        created_at: new Date().toISOString(),
    },
    {
        id: '50',
        type: 'credit',
        amount: 2000,
        currency: 'USD',
        category: '🧑‍💻 Freelance',
        created_at: new Date().toISOString(),
    },
];
