export const ACCOUNT_TYPES = [
    '💵 Cash',
    '🏦 Bank Accounts',
    '💰 Savings',
    '📈 Investment',
    '💳 Credit Card',
    '📉 Liability',
    '📱 Mobile Money',
    '💼 Other',
];

export const ACCOUNT_SUBGROUP_TYPES = {
    '💵 Cash': [
        '👛 Wallet',
        '💰 Petty Cash',
        '🏠 Home Safe',
        '🧳 Travel Cash',
        '💱 Foreign Currency',
    ],
    '🏦 Bank Accounts': [
        '🏦 Checking Account',
        '💵 Savings Account',
        '👥 Joint Account',
        '💼 Business Account',
        '🎓 Student Account',
        '📑 Fixed Deposit',
    ],
    '💰 Savings': [
        '🆘 Emergency Fund',
        '🏖️ Vacation Fund',
        '👴 Retirement Savings',
        '📚 Education Fund',
        '🏡 Down Payment',
        '📦 General Savings',
    ],
    '📈 Investment': [
        '📊 Stocks',
        '💵 Bonds',
        '📁 Mutual Funds',
        '📈 ETFs',
        '🏘️ Real Estate',
        '🪙 Crypto',
        '🥇 Commodities',
        '🤝 Private Equity',
    ],
    '💳 Credit Card': [
        '💳 Personal Credit Card',
        '💼 Business Credit Card',
        '🏷️ Store/Reward Card',
        '✈️ Travel Credit Card',
        '🔒 Secured Credit Card',
    ],
    '📉 Liability': [
        '🤝 Personal Loan',
        '🏠 Mortgage',
        '🎓 Student Loan',
        '🚗 Auto Loan',
        '🏢 Business Loan',
        '📉 Line of Credit',
        '🧾 Taxes Payable',
    ],
    '📱 Mobile Money': [
        '🌍 M-Pesa',
        '📱 MTN Mobile Money',
        '📲 AirtelTigo Money',
        '📡 Vodafone Cash',
        '💻 PayPal',
        '📲 CashApp',
        '💸 Venmo',
        '🌐 Other Wallets',
    ],
    '💼 Other': [
        '💳 Prepaid Card',
        '🎁 Gift Card Balance',
        '🏥 Employer Benefits',
        '🛡️ Insurance Cash Value',
        '🤲 Crowdfunding Wallet',
        '📦 Miscellaneous Assets',
    ],
};
