export const currencies = [
    {
        code: 'ALL',
        country: 'Albania',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/albania.png',
        locale: 'sq-AL',
        name: 'Lek',
        symbol: 'Lek',
        emojiFlag: '🇦🇱',
    },
    {
        code: 'AFN',
        country: 'Afghanistan',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/afghanistan.png',
        locale: 'uz-Arab-AF',
        name: 'Afghani',
        symbol: '؋',
        emojiFlag: '🇦🇫',
    },
    {
        code: 'ARS',
        country: 'Argentina',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/argentina.png',
        locale: 'es-AR',
        name: 'Peso',
        symbol: '$',
        emojiFlag: '🇦🇷',
    },
    {
        code: 'AWG',
        country: 'Aruba',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/aruba.png',
        locale: 'nl-AW',
        name: 'Guilder',
        symbol: 'ƒ',
        emojiFlag: '🇦🇼',
    },
    {
        code: 'AUD',
        country: 'Australia',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/australia.png',
        locale: 'en-AU',
        name: 'Dollar',
        symbol: '$',
        emojiFlag: '🇦🇺',
    },
    {
        code: 'AZN',
        country: 'Azerbaijan',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/azerbaijan.png',
        locale: 'az-Cyrl-AZ',
        name: 'Manat',
        symbol: '₼',
        emojiFlag: '🇦🇿',
    },
    {
        code: 'BSD',
        country: 'Bahamas',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/bahamas.png',
        locale: 'en-BS',
        name: 'Dollar',
        symbol: '$',
        emojiFlag: '🇧🇸',
    },
    {
        code: 'BBD',
        country: 'Barbados',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/barbados.png',
        locale: 'en-BB',
        name: 'Dollar',
        symbol: '$',
        emojiFlag: '🇧🇧',
    },
    {
        code: 'BYR',
        country: 'Belarus',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/belarus.png',
        locale: 'ru-BY',
        name: 'Ruble',
        symbol: 'p.',
        emojiFlag: '🇧🇾',
    },
    {
        code: 'BZD',
        country: 'Belize',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/belize.png',
        locale: 'en-BZ',
        name: 'Dollar',
        symbol: 'BZ$',
        emojiFlag: '🇧🇿',
    },
    {
        code: 'BMD',
        country: 'Bermuda',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/bermuda.png',
        locale: 'en-BM',
        name: 'Dollar',
        symbol: '$',
        emojiFlag: '🇧🇲',
    },
    {
        code: 'BOB',
        country: 'Bolivia',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/bolivia.png',
        locale: 'es-BO',
        name: 'Boliviano',
        symbol: '$b',
        emojiFlag: '🇧🇴',
    },
    {
        code: 'BAM',
        country: 'Bosnia and Herzegovina',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/Bosnia_and_Herzegovina.png',
        locale: 'bs-Latn-BA',
        name: 'Convertible Marka',
        symbol: 'KM',
        emojiFlag: '🇧🇦',
    },
    {
        code: 'BWP',
        country: 'Botswana',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/botswana.png',
        locale: 'en-BW',
        name: 'Pula',
        symbol: 'P',
        emojiFlag: '🇧🇼',
    },
    {
        code: 'BGN',
        country: 'Bulgaria',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/bulgaria.png',
        locale: 'bg-BG',
        name: 'Lev',
        symbol: 'лв',
        emojiFlag: '🇧🇬',
    },
    {
        code: 'BRL',
        country: 'Brazil',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/brazil.png',
        locale: 'pt-BR',
        name: 'Real',
        symbol: 'R$',
        emojiFlag: '🇧🇷',
    },
    {
        code: 'BND',
        country: 'Brunei',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/brunei.png',
        locale: 'ms-BN',
        name: 'Darussalam Dollar',
        symbol: '$',
        emojiFlag: '🇧🇳',
    },
    {
        code: 'KHR',
        country: 'Cambodia',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/cambodia.png',
        locale: 'km-KH',
        name: 'Riel',
        symbol: '៛',
        emojiFlag: '🇰🇭',
    },
    {
        code: 'CAD',
        country: 'Canada',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/canada.png',
        locale: 'en-CA',
        name: 'Dollar',
        symbol: '$',
        emojiFlag: '🇨🇦',
    },
    {
        code: 'KYD',
        country: 'Cayman Islands',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/Cayman_Islands.png',
        locale: 'en-KY',
        name: 'Dollar',
        symbol: '$',
        emojiFlag: '🇰🇾',
    },
    {
        code: 'CLP',
        country: 'Chile',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/chile.png',
        locale: 'es-CL',
        name: 'Peso',
        symbol: '$',
        emojiFlag: '🇨🇱',
    },
    {
        code: 'CNY',
        country: 'China',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/china.png',
        locale: 'zh-CN',
        name: 'Yuan Renminbi',
        symbol: '¥',
        emojiFlag: '🇨🇳',
    },
    {
        code: 'COP',
        country: 'Colombia',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/colombia.png',
        locale: 'es-CO',
        name: 'Peso',
        symbol: '$',
        emojiFlag: '🇨🇴',
    },
    {
        code: 'CRC',
        country: 'Costa Rica',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/costarica.png',
        locale: 'es-CR',
        name: 'Colon',
        symbol: '₡',
        emojiFlag: '🇨🇷',
    },
    {
        code: 'HRK',
        country: 'Croatia',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/croatia.png',
        locale: 'hr-HR',
        name: 'Kuna',
        symbol: 'kn',
        emojiFlag: '🇭🇷',
    },
    {
        code: 'CUP',
        country: 'Cuba',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/cuba.png',
        locale: 'cu',
        name: 'Peso',
        symbol: '₱',
        emojiFlag: '🇨🇺',
    },
    {
        code: 'CZK',
        country: 'Czech Republic',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/czechrepublic.png',
        locale: 'cs-CZ',
        name: 'Koruna',
        symbol: 'Kč',
        emojiFlag: '🇨🇿',
    },
    {
        code: 'DKK',
        country: 'Denmark',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/denmark.png',
        locale: 'en-DK',
        name: 'Krone',
        symbol: 'kr',
        emojiFlag: '🇩🇰',
    },
    {
        code: 'DOP',
        country: 'Dominican Republic',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/dominicanrepublic.png',
        locale: 'es-DO',
        name: 'Peso',
        symbol: 'RD$',
        emojiFlag: '🇩🇴',
    },
    {
        code: 'EGP',
        country: 'Egypt',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/egypt.png',
        locale: 'ar-EG',
        name: 'Pound',
        symbol: '£',
        emojiFlag: '🇪🇬',
    },
    {
        code: 'SVC',
        country: 'El Salvador',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/elsalvador.png',
        locale: 'es-SV',
        name: 'Colon',
        symbol: '$',
        emojiFlag: '🇸🇻',
    },
    {
        code: 'EEK',
        country: 'Estonia',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/estonia.png',
        locale: 'et-EE',
        name: 'Kroon',
        symbol: 'kr',
        emojiFlag: '🇪🇪',
    },
    {
        code: 'EUR',
        country: 'Euro Member',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/euro.png',
        locale: 'eu',
        name: 'Euro',
        symbol: '€',
        emojiFlag: '🇪🇺',
    },
    {
        code: 'FJD',
        country: 'Fiji',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/fiji.png',
        locale: 'en-FJ',
        name: 'Dollar',
        symbol: '$',
        emojiFlag: '🇫🇯',
    },
    {
        code: 'GEL',
        country: 'Georgia',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/georgia.png',
        locale: 'os-GE',
        name: 'Lari',
        symbol: '₾',
        emojiFlag: '🇬🇪',
    },
    {
        code: 'GHS',
        country: 'Ghana',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/ghana.png',
        locale: 'en-GH',
        name: 'Cedis',
        symbol: '¢',
        emojiFlag: '🇬🇭',
    },
    {
        code: 'GIP',
        country: 'Gibraltar',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/gibraltar.png',
        locale: 'en-GI',
        name: 'Pound',
        symbol: '£',
        emojiFlag: '🇬🇮',
    },
    {
        code: 'GTQ',
        country: 'Guatemala',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/guatemala.png',
        locale: 'es-GT',
        name: 'Quetzal',
        symbol: 'Q',
        emojiFlag: '🇬🇹',
    },
    {
        code: 'GGP',
        country: 'Guernsey',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/guernsey.png',
        locale: 'en-GG',
        name: 'Pound',
        symbol: '£',
        emojiFlag: '🇬🇬',
    },
    {
        code: 'GYD',
        country: 'Guyana',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/guyana.png',
        locale: 'es-GY',
        name: 'Dollar',
        symbol: '$',
        emojiFlag: '🇬🇾',
    },
    {
        code: 'HNL',
        country: 'Honduras',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/honduras.png',
        locale: 'es-HN',
        name: 'Lempira',
        symbol: 'L',
        emojiFlag: '🇭🇳',
    },
    {
        code: 'HKD',
        country: 'Hong Kong',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/hongkong.png',
        locale: 'en-HK',
        name: 'Dollar',
        symbol: '$',
        emojiFlag: '🇭🇰',
    },
    {
        code: 'HUF',
        country: 'Hungary',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/hungary.png',
        locale: 'hu-HU',
        name: 'Forint',
        symbol: 'Ft',
        emojiFlag: '🇭🇺',
    },
    {
        code: 'ISK',
        country: 'Iceland',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/iceland.png',
        locale: 'is-IS',
        name: 'Krona',
        symbol: 'kr',
        emojiFlag: '🇮🇸',
    },
    {
        code: 'INR',
        country: 'India',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/india.png',
        locale: 'en-IN',
        name: 'Rupee',
        symbol: '₹',
        emojiFlag: '🇮🇳',
    },
    {
        code: 'IDR',
        country: 'Indonesia',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/indonesia.png',
        locale: 'id-ID',
        name: 'Rupiah',
        symbol: 'Rp',
        emojiFlag: '🇮🇩',
    },
    {
        code: 'IRR',
        country: 'Iran',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/iran.png',
        locale: 'fa-IR',
        name: 'Rial',
        symbol: '﷼',
        emojiFlag: '🇮🇷',
    },
    {
        code: 'ILS',
        country: 'Israel',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/israel.png',
        locale: 'en-IL',
        name: 'Shekel',
        symbol: '₪',
        emojiFlag: '🇮🇱',
    },
    {
        code: 'JMD',
        country: 'Jamaica',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/jamaica.png',
        locale: 'en-JM',
        name: 'Dollar',
        symbol: 'J$',
        emojiFlag: '🇯🇲',
    },
    {
        code: 'JPY',
        country: 'Japan',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/japan.png',
        locale: 'ja-JP',
        name: 'Yen',
        symbol: '¥',
        emojiFlag: '🇯🇵',
    },
    {
        code: 'KZT',
        country: 'Kazakhstan',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/kazakhstan.png',
        locale: 'ru-KZ',
        name: 'Tenge',
        symbol: 'лв',
        emojiFlag: '🇰🇿',
    },
    {
        code: 'KRW',
        country: 'Korea (South)',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/southkorea.png',
        locale: 'ko-KR',
        name: 'Won',
        symbol: '₩',
        emojiFlag: '🇰🇷',
    },
    {
        code: 'KGS',
        country: 'Kyrgyzstan',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/kyrgyzstan.png',
        locale: 'ky-KG',
        name: 'Som',
        symbol: 'лв',
        emojiFlag: '🇰🇬',
    },
    {
        code: 'LAK',
        country: 'Laos',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/laos.png',
        locale: 'la',
        name: 'Kip',
        symbol: '₭',
        emojiFlag: '🇱🇦',
    },
    {
        code: 'LVL',
        country: 'Latvia',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/latvia.png',
        locale: 'lv',
        name: 'Lat',
        symbol: 'Ls',
        emojiFlag: '🇱🇻',
    },
    {
        code: 'LBP',
        country: 'Lebanon',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/lebanon.png',
        locale: 'ar-LB',
        name: 'Pound',
        symbol: '£',
        emojiFlag: '🇱🇧',
    },
    {
        code: 'LRD',
        country: 'Liberia',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/liberia.png',
        locale: 'en-LR',
        name: 'Dollar',
        symbol: '$',
        emojiFlag: '🇱🇷',
    },
    {
        code: 'LTL',
        country: 'Lithuania',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/lithuania.png',
        locale: 'lt-LT',
        name: 'Litas',
        symbol: 'Lt',
        emojiFlag: '🇱🇹',
    },
    {
        code: 'MKD',
        country: 'Macedonia',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/macedonia.png',
        locale: 'mk',
        name: 'Denar',
        symbol: 'ден',
        emojiFlag: '🇲🇰',
    },
    {
        code: 'MYR',
        country: 'Malaysia',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/malaysia.png',
        locale: 'ms-MY',
        name: 'Ringgit',
        symbol: 'RM',
        emojiFlag: '🇲🇾',
    },
    {
        code: 'MUR',
        country: 'Mauritius',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/mauritius.png',
        locale: 'en-MU',
        name: 'Rupee',
        symbol: '₨',
        emojiFlag: '🇲🇺',
    },
    {
        code: 'MXN',
        country: 'Mexico',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/mexico.png',
        locale: 'es-MX',
        name: 'Peso',
        symbol: '$',
        emojiFlag: '🇲🇽',
    },
    {
        code: 'MNT',
        country: 'Mongolia',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/mongolia.png',
        locale: 'mn-MN',
        name: 'Tughrik',
        symbol: '₮',
        emojiFlag: '🇲🇳',
    },
    {
        code: 'MZN',
        country: 'Mozambique',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/mozambique.png',
        locale: 'pt-MZ',
        name: 'Metical',
        symbol: 'MT',
        emojiFlag: '🇲🇿',
    },
    {
        code: 'NAD',
        country: 'Namibia',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/namibia.png',
        locale: 'en-NA',
        name: 'Dollar',
        symbol: '$',
        emojiFlag: '🇳🇦',
    },
    {
        code: 'NPR',
        country: 'Nepal',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/nepal.png',
        locale: 'ne-NP',
        name: 'Rupee',
        symbol: '₨',
        emojiFlag: '🇳🇵',
    },
    {
        code: 'ANG',
        country: 'Netherlands',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/netherlands.png',
        locale: 'nl-NL',
        name: 'Antilles Guilder',
        symbol: 'ƒ',
        emojiFlag: '🇳🇱',
    },
    {
        code: 'NZD',
        country: 'New Zealand',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/newzealand.png',
        locale: 'en-NZ',
        name: 'Dollar',
        symbol: '$',
        emojiFlag: '🇳🇿',
    },
    {
        code: 'NIO',
        country: 'Nicaragua',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/nicaragua.png',
        locale: 'es-NI',
        name: 'Cordoba',
        symbol: 'C$',
        emojiFlag: '🇳🇮',
    },
    {
        code: 'NGN',
        country: 'Nigeria',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/nigeria.png',
        locale: 'ig-NG',
        name: 'Naira',
        symbol: '₦',
        emojiFlag: '🇳🇬',
    },
    {
        code: 'NOK',
        country: 'Norway',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/norway.png',
        locale: 'nb-NO',
        name: 'Krone',
        symbol: 'kr',
        emojiFlag: '🇳🇴',
    },
    {
        code: 'OMR',
        country: 'Oman',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/oman.png',
        locale: 'ar-OM',
        name: 'Rial',
        symbol: '﷼',
        emojiFlag: '🇴🇲',
    },
    {
        code: 'PKR',
        country: 'Pakistan',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/pakistan.png',
        locale: 'en-PK',
        name: 'Rupee',
        symbol: '₨',
        emojiFlag: '🇵🇰',
    },
    {
        code: 'PAB',
        country: 'Panama',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/panama.png',
        locale: 'es-PA',
        name: 'Balboa',
        symbol: 'B/.',
        emojiFlag: '🇵🇦',
    },
    {
        code: 'PYG',
        country: 'Paraguay',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/paraguay.png',
        locale: 'es-PY',
        name: 'Guarani',
        symbol: 'Gs',
        emojiFlag: '🇵🇾',
    },
    {
        code: 'PEN',
        country: 'Peru',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/peru.png',
        locale: 'es-PE',
        name: 'Nuevo Sol',
        symbol: 'S/.',
        emojiFlag: '🇵🇪',
    },
    {
        code: 'PHP',
        country: 'Philippines',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/philippines.png',
        locale: 'en-PH',
        name: 'Peso',
        symbol: '₱',
        emojiFlag: '🇵🇭',
    },
    {
        code: 'PLN',
        country: 'Poland',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/poland.png',
        locale: 'pl-PL',
        name: 'Zloty',
        symbol: 'zł',
        emojiFlag: '🇵🇱',
    },
    {
        code: 'QAR',
        country: 'Qatar',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/qatar.png',
        locale: 'ar-QA',
        name: 'Riyal',
        symbol: '﷼',
        emojiFlag: '🇶🇦',
    },
    {
        code: 'RON',
        country: 'Romania',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/romania.png',
        locale: 'ro-RO',
        name: 'New Leu',
        symbol: 'lei',
        emojiFlag: '🇷🇴',
    },
    {
        code: 'RUB',
        country: 'Russia',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/russia.png',
        locale: 'ru-RU',
        name: 'Ruble',
        symbol: '₽',
        emojiFlag: '🇷🇺',
    },
    {
        code: 'SAR',
        country: 'Saudi Arabia',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/saudiarabia.png',
        locale: 'ar-SA',
        name: 'Riyal',
        symbol: '﷼',
        emojiFlag: '🇸🇦',
    },
    {
        code: 'RSD',
        country: 'Serbia',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/serbia.png',
        locale: 'sr-Latn-RS',
        name: 'Dinar',
        symbol: 'Дин.',
        emojiFlag: '🇷🇸',
    },
    {
        code: 'SCR',
        country: 'Seychelles',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/seychelles.png',
        locale: 'en-SC',
        name: 'Rupee',
        symbol: '₨',
        emojiFlag: '🇸🇨',
    },
    {
        code: 'SGD',
        country: 'Singapore',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/singapore.png',
        locale: 'ms-SG',
        name: 'Dollar',
        symbol: '$',
        emojiFlag: '🇸🇬',
    },
    {
        code: 'SBD',
        country: 'Solomon Islands',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/solomonislands.png',
        locale: 'en-SB',
        name: 'Dollar',
        symbol: '$',
        emojiFlag: '🇸🇧',
    },
    {
        code: 'SOS',
        country: 'Somalia',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/somalia.png',
        locale: 'so-SO',
        name: 'Shilling',
        symbol: 'S',
        emojiFlag: '🇸🇴',
    },
    {
        code: 'ZAR',
        country: 'South Africa',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/southafrica.png',
        locale: 'en-ZA',
        name: 'Rand',
        symbol: 'R',
        emojiFlag: '🇿🇦',
    },
    {
        code: 'LKR',
        country: 'Sri Lanka',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/srilanka.png',
        locale: 'ta-LK',
        name: 'Rupee',
        symbol: '₨',
        emojiFlag: '🇱🇰',
    },
    {
        code: 'SEK',
        country: 'Sweden',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/sweden.png',
        locale: 'sv-SE',
        name: 'Krona',
        symbol: 'kr',
        emojiFlag: '🇸🇪',
    },
    {
        code: 'CHF',
        country: 'Switzerland',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/switzerland.png',
        locale: 'en-CH',
        name: 'Franc',
        symbol: 'CHF',
        emojiFlag: '🇨🇭',
    },
    {
        code: 'SRD',
        country: 'Suriname',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/suriname.png',
        locale: 'nl-SR',
        name: 'Dollar',
        symbol: '$',
        emojiFlag: '🇸🇷',
    },
    {
        code: 'SYP',
        country: 'Syria',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/syria.png',
        locale: 'ar-SY',
        name: 'Pound',
        symbol: '£',
        emojiFlag: '🇸🇾',
    },
    {
        code: 'TWD',
        country: 'Taiwan',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/taiwan.png',
        locale: 'zh-Hant-TW',
        name: 'New Dollar',
        symbol: 'NT$',
        emojiFlag: '🇹🇼',
    },
    {
        code: 'THB',
        country: 'Thailand',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/thailand.png',
        locale: 'th-TH',
        name: 'Baht',
        symbol: '฿',
        emojiFlag: '🇹🇭',
    },
    {
        code: 'TTD',
        country: 'Trinidad and Tobago',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/trinidadandtobago.png',
        locale: 'en-TT',
        name: 'Dollar',
        symbol: 'TT$',
        emojiFlag: '🇹🇹',
    },
    {
        code: 'TRL',
        country: 'Turkey',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/turkey.png',
        locale: 'tr-TR',
        name: 'Lira',
        symbol: '₺',
        emojiFlag: '🇹🇷',
    },
    {
        code: 'TVD',
        country: 'Tuvalu',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/tuvalu.png',
        locale: 'en-TV',
        name: 'Dollar',
        symbol: '$',
        emojiFlag: '🇹🇻',
    },
    {
        code: 'UAH',
        country: 'Ukraine',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/ukraine.png',
        locale: 'uk-UA',
        name: 'Hryvna',
        symbol: '₴',
        emojiFlag: '🇺🇦',
    },
    {
        code: 'GBP',
        country: 'United Kingdom',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/unitedkingdom.png',
        locale: 'en-GB',
        name: 'Pound Sterling',
        symbol: '£',
        emojiFlag: '🇬🇧',
    },
    {
        code: 'USD',
        country: 'United States',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/unitedstates.png',
        locale: 'en-US',
        name: 'US Dollar',
        symbol: '$',
        emojiFlag: '🇺🇸',
    },
    {
        code: 'UYU',
        country: 'Uruguay',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/uruguay.png',
        locale: 'es-UY',
        name: 'Peso',
        symbol: '$U',
        emojiFlag: '🇺🇾',
    },
    {
        code: 'UZS',
        country: 'Uzbekistan',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/uzbekistan.png',
        locale: 'uz-Latn-UZ',
        name: 'Som',
        symbol: 'лв',
        emojiFlag: '🇺🇿',
    },
    {
        code: 'VEF',
        country: 'Venezuela',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/venezuela.png',
        locale: 'az-Cyrl-AZ',
        name: 'Bolivar Fuerte',
        symbol: 'Bs',
        emojiFlag: '🇻🇪',
    },
    {
        code: 'VND',
        country: 'Vietnam',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/vietnam.png',
        locale: 'vi-VN',
        name: 'Dong',
        symbol: '₫',
        emojiFlag: '🇻🇳',
    },
    {
        code: 'YER',
        country: 'Yemen',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/yemen.png',
        locale: 'ar-YE',
        name: 'Rial',
        symbol: '﷼',
        emojiFlag: '🇾🇪',
    },
    {
        code: 'ZMW',
        country: 'Zambia',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/sambia.png',
        locale: 'en-ZW',
        name: 'Kwacha',
        symbol: 'ZK',
        emojiFlag: '🇿🇲',
    },
    {
        code: 'ZWD',
        country: 'Zimbabwe',
        flag: 'https://www.currencyremitapp.com/wp-content/themes/currencyremitapp/images/countryimages/zimbabwe.png',
        locale: 'en-ZW',
        name: 'Dollar',
        symbol: 'Z$',
        emojiFlag: '🇿🇼',
    },
] as const;
