export const TRANSACTION_TYPES = [
    { key: 'debit', label: 'Expense' },
    { key: 'credit', label: 'Income' },
    { key: 'transfer', label: 'Transfer' },
];

export const transactionTypes = [
    '🍲 Food',
    '🚗 Transport',
    '🏠 Rent',
    '💡 Utilities',
    '📱 Phone',
    '💻 Internet',
    '🛒 Groceries',
    '👗 Clothing',
    '🏥 Healthcare',
    '💊 Medications',
    '🎓 Education',
    '📚 Books',
    '🎉 Entertainment',
    '🍿 Movies',
    '🎮 Games',
    '🏋️ Gym',
    '✈️ Travel',
    '🏖️ Vacation',
    '🎁 Gifts',
    '💼 Work',
    '📈 Investments',
    '💳 Credit Card',
    '🏦 Savings',
    '🚿 Personal Care',
    '🐾 Pet Care',
    '🛠️ Maintenance',
    '🛏️ Furniture',
    '🖼️ Decor',
    '🧹 Cleaning',
    '🛡️ Insurance',
    '🚨 Security',
    '📦 Subscriptions',
    '💸 Miscellaneous',
    '💰 Wages',
];
