// export const transactions = [
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 11,
//         category: 'Test',
//         created_at: '2025-08-01T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '1',
//         note: 'Mock transaction 1',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-01T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 12,
//         category: 'Test',
//         created_at: '2025-08-01T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '2',
//         note: 'Mock transaction 2',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-01T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 13,
//         category: 'Test',
//         created_at: '2025-08-01T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '3',
//         note: 'Mock transaction 3',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-01T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 14,
//         category: 'Test',
//         created_at: '2025-08-01T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '4',
//         note: 'Mock transaction 4',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-01T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 165.78,
//         category: 'Test',
//         created_at: '2025-08-03T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '5',
//         note: 'Mock transaction 5',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-03T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 166.78,
//         category: 'Test',
//         created_at: '2025-08-03T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '6',
//         note: 'Mock transaction 6',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-03T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 303.94,
//         category: 'Test',
//         created_at: '2025-08-04T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '7',
//         note: 'Mock transaction 7',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-04T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 310.42,
//         category: 'Test',
//         created_at: '2025-08-04T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '8',
//         note: 'Mock transaction 8',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-04T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 622.25,
//         category: 'Test',
//         created_at: '2025-08-06T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '9',
//         note: 'Mock transaction 9',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-06T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 1231.2,
//         category: 'Test',
//         created_at: '2025-08-09T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '10',
//         note: 'Mock transaction 10',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-09T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 1302.74,
//         category: 'Test',
//         created_at: '2025-08-09T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '11',
//         note: 'Mock transaction 11',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-09T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 1658.06,
//         category: 'Test',
//         created_at: '2025-08-11T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '12',
//         note: 'Mock transaction 12',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-11T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 2291.65,
//         category: 'Test',
//         created_at: '2025-08-13T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '13',
//         note: 'Mock transaction 13',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-13T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 2292.65,
//         category: 'Test',
//         created_at: '2025-08-13T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '14',
//         note: 'Mock transaction 14',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-13T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 2293.65,
//         category: 'Test',
//         created_at: '2025-08-13T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '15',
//         note: 'Mock transaction 15',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-13T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 2294.65,
//         category: 'Test',
//         created_at: '2025-08-13T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '16',
//         note: 'Mock transaction 16',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-13T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 2295.65,
//         category: 'Test',
//         created_at: '2025-08-13T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '17',
//         note: 'Mock transaction 17',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-13T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 2624.71,
//         category: 'Test',
//         created_at: '2025-08-14T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '18',
//         note: 'Mock transaction 18',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-14T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 2625.71,
//         category: 'Test',
//         created_at: '2025-08-14T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '19',
//         note: 'Mock transaction 19',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-14T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 2689.35,
//         category: 'Test',
//         created_at: '2025-08-14T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '20',
//         note: 'Mock transaction 20',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-14T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 3036.96,
//         category: 'Test',
//         created_at: '2025-08-15T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '21',
//         note: 'Mock transaction 21',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-15T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 3037.96,
//         category: 'Test',
//         created_at: '2025-08-15T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '22',
//         note: 'Mock transaction 22',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-15T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 3038.96,
//         category: 'Test',
//         created_at: '2025-08-15T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '23',
//         note: 'Mock transaction 23',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-15T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 3039.96,
//         category: 'Test',
//         created_at: '2025-08-15T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '24',
//         note: 'Mock transaction 24',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-15T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 3040.96,
//         category: 'Test',
//         created_at: '2025-08-15T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '25',
//         note: 'Mock transaction 25',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-15T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 3204.54,
//         category: 'Test',
//         created_at: '2025-08-16T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '26',
//         note: 'Mock transaction 26',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-16T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 3205.54,
//         category: 'Test',
//         created_at: '2025-08-16T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '27',
//         note: 'Mock transaction 27',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-16T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 3206.54,
//         category: 'Test',
//         created_at: '2025-08-16T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '28',
//         note: 'Mock transaction 28',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-16T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 3296.95,
//         category: 'Test',
//         created_at: '2025-08-16T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '29',
//         note: 'Mock transaction 29',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-16T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 3297.95,
//         category: 'Test',
//         created_at: '2025-08-16T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '30',
//         note: 'Mock transaction 30',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-16T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 3648.56,
//         category: 'Test',
//         created_at: '2025-08-17T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '31',
//         note: 'Mock transaction 31',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-17T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 3945.57,
//         category: 'Test',
//         created_at: '2025-08-18T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '32',
//         note: 'Mock transaction 32',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-18T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 3946.57,
//         category: 'Test',
//         created_at: '2025-08-18T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '33',
//         note: 'Mock transaction 33',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-18T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 3947.57,
//         category: 'Test',
//         created_at: '2025-08-18T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '34',
//         note: 'Mock transaction 34',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-18T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 4306.81,
//         category: 'Test',
//         created_at: '2025-08-19T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '35',
//         note: 'Mock transaction 35',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-19T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 4307.81,
//         category: 'Test',
//         created_at: '2025-08-19T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '36',
//         note: 'Mock transaction 36',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-19T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 4354.9,
//         category: 'Test',
//         created_at: '2025-08-19T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '37',
//         note: 'Mock transaction 37',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-19T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 4355.9,
//         category: 'Test',
//         created_at: '2025-08-19T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '38',
//         note: 'Mock transaction 38',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-19T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 5940.55,
//         category: 'Test',
//         created_at: '2025-08-23T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '39',
//         note: 'Mock transaction 39',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-23T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 5941.55,
//         category: 'Test',
//         created_at: '2025-08-23T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '40',
//         note: 'Mock transaction 40',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-23T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 5942.55,
//         category: 'Test',
//         created_at: '2025-08-23T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '41',
//         note: 'Mock transaction 41',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-23T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 5943.55,
//         category: 'Test',
//         created_at: '2025-08-23T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '42',
//         note: 'Mock transaction 42',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-23T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 5944.55,
//         category: 'Test',
//         created_at: '2025-08-23T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '43',
//         note: 'Mock transaction 43',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-23T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 6070.31,
//         category: 'Test',
//         created_at: '2025-08-24T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '44',
//         note: 'Mock transaction 44',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-24T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 6173.33,
//         category: 'Test',
//         created_at: '2025-08-24T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '45',
//         note: 'Mock transaction 45',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-24T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 6187.03,
//         category: 'Test',
//         created_at: '2025-08-24T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '46',
//         note: 'Mock transaction 46',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-24T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 6664.06,
//         category: 'Test',
//         created_at: '2025-08-25T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '47',
//         note: 'Mock transaction 47',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-25T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 6665.06,
//         category: 'Test',
//         created_at: '2025-08-26T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '48',
//         note: 'Mock transaction 48',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-26T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 6964.46,
//         category: 'Test',
//         created_at: '2025-08-26T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '49',
//         note: 'Mock transaction 49',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-26T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 7001.97,
//         category: 'Test',
//         created_at: '2025-08-26T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '50',
//         note: 'Mock transaction 50',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-26T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 7564.14,
//         category: 'Test',
//         created_at: '2025-08-27T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '51',
//         note: 'Mock transaction 51',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-27T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 7565.14,
//         category: 'Test',
//         created_at: '2025-08-27T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '52',
//         note: 'Mock transaction 52',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-27T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 7672.53,
//         category: 'Test',
//         created_at: '2025-08-27T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '53',
//         note: 'Mock transaction 53',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-27T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 7673.53,
//         category: 'Test',
//         created_at: '2025-08-27T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '54',
//         note: 'Mock transaction 54',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-27T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 7674.53,
//         category: 'Test',
//         created_at: '2025-08-27T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '55',
//         note: 'Mock transaction 55',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-27T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 7984.82,
//         category: 'Test',
//         created_at: '2025-08-28T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '56',
//         note: 'Mock transaction 56',
//         plan_id: '',
//         to_account: '',
//         type: 'debit',
//         updated_at: '2025-08-28T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 7985.82,
//         category: 'Test',
//         created_at: '2025-08-29T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '57',
//         note: 'Mock transaction 57',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-29T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 8558.97,
//         category: 'Test',
//         created_at: '2025-08-29T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '58',
//         note: 'Mock transaction 58',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-29T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 8559.97,
//         category: 'Test',
//         created_at: '2025-08-30T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '59',
//         note: 'Mock transaction 59',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-30T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 8560.97,
//         category: 'Test',
//         created_at: '2025-08-30T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '60',
//         note: 'Mock transaction 60',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-30T00:00:00.000Z',
//         user_id: 'user1',
//     },
//     {
//         account: {},
//         account_id: 'acc1',
//         amount: 9435.78,
//         category: 'Test',
//         created_at: '2025-08-31T00:00:00.000Z',
//         currency: 'GHS',
//         deleted_at: null,
//         from_account: '',
//         id: '61',
//         note: 'Mock transaction 61',
//         plan_id: '',
//         to_account: '',
//         type: 'credit',
//         updated_at: '2025-08-31T00:00:00.000Z',
//         user_id: 'user1',
//     },
// ];

import { generateMockTransactionsForMonth } from '../Stats/utils';

export const transactions = generateMockTransactionsForMonth(new Date(), true);
