import './globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Nav from '@/components/shared/Nav';
import Footer from '@/components/shared/Footer';
import { Analytics } from '@vercel/analytics/react';

const satoshi = localFont({
    src: '../../public/fonts/satoshi/Satoshi-Variable.woff2',
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${satoshi.className} antialiased relative`}>
                <Analytics />
                {/* <div className='fixed top-0 left-0 w-full z-50'> */}
                <Nav />
                {/* </div> */}
                {children}
                <Footer />
            </body>
        </html>
    );
}
