name: Build and Release APK

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build Docker image
              run: docker build --build-arg EXPO_TOKEN=${{ secrets.EXPO_TOKEN }} -t purple .

            - name: Run Docker container to build APK
              run: |
                  docker run --rm \
                    -e EXPO_TOKEN=GWByotFGL1iXR1CgN5Z2oDPCAY4yL49tGXsiHpYG \
                    -e EAS_NO_VCS=1 \
                    -v "$(pwd)":/project/app \
                    purple

            - name: Upload APK to Releases
              uses: actions/upload-release-asset@v1
              with:
                  asset_path: ./output/app-release.apk
                  asset_name: app-release.apk
                  token: ${{ secrets.GITHUB_TOKEN }}
