name: Build Android App

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker
              uses: docker/setup-buildx-action@v1

            - name: Build Docker image
              run: docker build -t purple .

            - name: Run Docker container
              run: docker run -v ${{ github.workspace }}/output:/output purple

            - name: Archive APK
              uses: actions/upload-artifact@v2
              with:
                  name: purple-debug.apk
                  path: output/purple-debug.apk
