name: Build and Release APK

on:
    push:
        branches:
            - master
            - develop
            - dev

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: purple

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Java 17
              uses: actions/setup-java@v2
              with:
                  distribution: "adopt"
                  java-version: "17"
                  java-package: jdk
                  cache: "gradle"

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20.4.0"
                  cache: "yarn"

            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
              with:
                  gradle-version: 7.6

            - name: Install EAS CLI and dependencies
              run: |
                  npm install -g eas-cli @expo/ngrok@^4.1.0 sharp-cli@^2.1.0
                  sudo apt update && sudo apt install -y wget unzip
                  wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip && unzip commandlinetools-linux-9477386_latest.zip
                  sudo mkdir -p /android-sdk/cmdline-tools/latest && sudo mv cmdline-tools/* /android-sdk/cmdline-tools/latest
                  sudo yes | /android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

            - name: Set up Android SDK
              run: |
                  echo "export ANDROID_SDK_ROOT=/android-sdk" >> $GITHUB_ENV
                  echo "export PATH=$PATH:/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_ENV

            - name: Configure Gradle memory
              run: |
                  mkdir -p android/gradle/
                  echo "org.gradle.jvmargs=-Xmx4g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError" > android/gradle.properties
                  echo "org.gradle.parallel=true" >> android/gradle.properties
                  echo "org.gradle.configureondemand=true" >> android/gradle.properties
                  echo "org.gradle.daemon=false" >> android/gradle.properties

            - name: Install Yarn
              run: npm install -g yarn

            - name: Install project dependencies
              run: |
                  yarn install
                  yarn cache clean

            - name: Create .env file for build
              run: |
                  echo "EXPO_PUBLIC_API_URL=${{ secrets.API_URL }}" > .env
                  echo "EXPO_PUBLIC_API_KEY=${{secrets.API_KEY}}" >> .env

            - name: Build APK
              run: |
                  export GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx4g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError"
                  eas build -p android --profile development --local --output purple.apk
              env:
                  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
                  EAS_NO_VCS: 1

            - name: Upload binaries to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: purple/purple.apk
                  asset_name: Purple.apk
                  tag: ${{ github.ref }}
                  overwrite: true
                  body: "New app release"
