name: Generate new version number
on:
    push:
        branches:
            - release

jobs:
    broker_version_ci_pipeline:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: apps/broker

        steps:
            - uses: actions/checkout@v3

            - name: Bump version and push tag
              id: changelog
              uses: TriPSs/conventional-changelog-action@v3
              # only generate new version if the branch is the release branch
              if: ${{ github.ref == 'refs/heads/release' }}
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  git-message: "chore(release): {version}"
                  preset: "angular"
                  tag-prefix: "v"
                  release-count: 1
                  output-file: "./CHANGELOG.md"
                  version-file: "./package.json"
                  skip-on-empty: true
